# Generated by Django 4.2 on 2023-04-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_attandance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attandance",
        ),
    ]
