# Generated by Django 4.2 on 2023-04-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_delete_attandance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attandance",
            fields=[
                ("attandance_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40)),
                ("Date", models.CharField(max_length=20)),
                ("time", models.CharField(max_length=20)),
                ("Date_Time", models.CharField(max_length=20)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.company"
                    ),
                ),
                (
                    "device_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.device"
                    ),
                ),
                (
                    "employ_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.employ"
                    ),
                ),
            ],
        ),
    ]
