# Generated by Django 4.2 on 2023-04-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0011_employ_attandance"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employ",
            new_name="Employee",
        ),
    ]
