# Generated by Django 4.2 on 2023-04-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0012_rename_employ_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="device_id",
        ),
        migrations.DeleteModel(
            name="Attandance",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
