# Generated by Django 4.2 on 2023-04-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0016_alter_newemployee_card_no"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attandance",
        ),
    ]
