# Generated by Django 4.2 on 2023-04-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0018_attandance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attandance",
            name="employee_id",
        ),
    ]
