# Generated by Django 4.2 on 2023-04-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0019_remove_attandance_employee_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attandance",
        ),
    ]
