# Generated by Django 4.2 on 2023-04-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0021_attandance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attandance",
        ),
    ]
