# Generated by Django 4.2 on 2023-04-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0024_alter_attandance_date_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attandance",
        ),
    ]
