# Generated by Django 4.2 on 2023-05-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0026_attandance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attandance",
        ),
    ]
