# Generated by Django 4.2 on 2023-05-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0030_attandance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attandance",
        ),
    ]
